title: Naz Col
description: Personal site
theme: minima
# Optional: basic nav
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/doganazcol" }

header_pages:
  - index.md
  - sidekicks.md
